project/urls.py
from django.contrib import admin
from django.urls import path, include
import school_app.views as school_app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('school_app.urls')),
]

school_app/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('signup/', views.Signup, name='signup'),
    # path('login/', views.MyLoginView.as_view(), name='login'),
    path('login/', views.Login, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('user_/', views.MyUserView.as_view(), name='user_'),
    path('other/', views.MyOtherView.as_view(), name='other'),
    path('teacher/',views.TeacherView.as_view(), name='teacher'),
]

school_app/models.py
from django.db import models
from users.models import CustomUser

# Create your models here.


class CleaningModel(models.Model):
    PLACE_CHOICES =((0,"教室ほうき"),(1,"教室机寄せ"),(2,"教室モップ"),(3,"黒板"),(4,"理科室"),(5,"男子トイレ"),(6,"女子トイレ"),(7,"美化委員の仕事"))
    user = models.ForeignKey(CustomUser,on_delete = models.CASCADE)
    place = models.IntegerField(choices = PLACE_CHOICES)



class SchoolLunchModel(models.Model):
    ABC_CHOICES =(("A","A"),("B","B"),("C","C"))

    user = models.ForeignKey(CustomUser,on_delete = models.CASCADE)
    ABC = models.CharField(choices = ABC_CHOICES,max_length = 1)

class DayDutyModel(models.Model):
    current_number = models.IntegerField(default = 1)
    classnum = models.IntegerField(blank=True, default = 0)
    gradenum = models.IntegerField(blank=True, default = 0)
    #daydutyクラスごとに違う。年と組のfieldが必要。

class ScheduleModel(models.Model):
    monday =models.CharField(max_length = 7)
    tuesday =models.CharField(max_length = 7)
    wednesday =models.CharField(max_length = 7)
    thursday =models.CharField(max_length = 7)
    friday =models.CharField(max_length = 7)
    classnum = models.IntegerField(blank=True, default = 0)
    gradenum = models.IntegerField(blank=True, default = 0)

class MessageModel(models.Model):
    CATEGORYCHOICES = ((0,"お知らせ"),(1,"重要"))
    teacher = models.ForeignKey(CustomUser,on_delete = models.CASCADE)
    message = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add = True)
    category = models.IntegerField(choices=CATEGORYCHOICES)



#class DayDutyModel(models.Model):
    #外部キー


#class AbsentDateModel(models.Model):

    #datetime = models.DateTimeField()

school_app/forms.py
from django import forms
from django.forms import Widget
from school_app.models import DayDutyModel, ScheduleModel, MessageModel
from users.models import CustomUser
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'classnum', 'gradenum', 'attendancenum', 'username', 'email', 'password1', 'password2']
        labels = {'first_name':'名前','last_name':'苗字', 'classnum':'クラス', 'gradenum':'学年', 'attendancenum':'出席番号', 'username':'ユーザーネーム', 'email':'emailアドレス', 'password1':'パスワード1', 'password2':'パスワード2'}

class LoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'password']
        labels = {'email':'emailアドレス','password':'パスワード'}

class ScheduleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['monday'].widget.attrs['class'] = 'monday'
        self.fields['tuesday'].widget.attrs['class'] = 'tuesday'
        self.fields['wednesday'].widget.attrs['class'] = 'wednesday'
        self.fields['thursday'].widget.attrs['class'] = 'thursday'
        self.fields['friday'].widget.attrs['class'] = 'friday'

    class Meta:
        model = ScheduleModel
        fields = ['monday','tuesday','wednesday','thursday','friday']
        labels = {'monday':'月曜日','tuesday':'火曜日','wednesday':'水曜日','thursday':'木曜日','friday':'金曜日'} # def __init__(self,*args,**kwargs):
        # super(ScheduleForm,self).__init__(*args,**kwargs)
        # self.fields['monday'].initial = self.model.objects.monday

class DaydutyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['current_number'].widget.attrs['class'] = 'current_num'

    class Meta:
        model = DayDutyModel
        fields = ['current_number']
        labels = {'current_number':'日直の出席番号'}

class MessageForm(forms.Form):
    message = forms.CharField(
    required=True,
    label = 'メッセージ',
    max_length=1024,
    widget=forms.Textarea(
        attrs={
            'placeholder': '内容を1,024文字以内で入力してください。',
        }
    )
    )
    is_important = forms.BooleanField(
        label = '重要',
        required = False,
        widget = forms.CheckboxInput(attrs={'class':'check'})
    )

    # def __init__(self,*args,**kwargs):
        # super(ScheduleForm,self).__init__(*args,**kwargs)
        # self.fields['monday'].initial = self.model.objects.monday

# class CleaningForm(forms.ModelForm):
#     class Meta:
#         model = CleaningModel
#         fields = ['place']
#         labels = {'place':'場所(0なら教室ほうき 1なら教室机寄せ 2なら教室モップ 3なら黒板 4なら理科室 5なら男子トイレ 6なら女子トイレ 7なら美化委員の仕事)'}

school_app/views.py
from calendar import MONDAY
from .forms import SignupForm, LoginForm, ScheduleForm, DaydutyForm, MessageForm
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import CleaningModel, DayDutyModel, ScheduleModel, SchoolLunchModel, MessageModel
from users.models import CustomUser
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout



# class MySignupView(CreateView):
#     template_name = 'login/signup.html'
#     form_class = SignupForm
#     success_url = '/user/'

#     def get_context_data(self):
#         context = super().get_context_data()
#         context['form_cleaning'] = CleaningForm()
#         return context

#     def form_valid(self, form):
#         result = super().form_valid(form)
#         user = self.object
#         if form.is_valid and user is not None:
#             login(self.request, user)
#             CleaningModel.create(user = user)
        
#         return result

def Signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        place= request.POST.get('place')
        schoollunch = request.POST.get('schoollunch')
        if form.is_valid() and place in {"0","1","2","3","4","5","6","7"} and schoollunch in {"A","B","C"}:
            form.save()
            username = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            CleaningModel.objects.create(user = user, place = int(place) )
            SchoolLunchModel.objects.create(user = user, ABC = schoollunch)

            login(request, user)
           
            return redirect('login')
    else:
        form = SignupForm()
    return render(request, 'login/signup.html', {'form': form})


def Login(request):
    # POST
    if request.method == 'POST':
        # フォーム入力のユーザーID・パスワード取得
        Email = request.POST.get('email')
        Pass = request.POST.get('password')
    

        # Djangoの認証機能
        print(Email, Pass)
        # user = CustomUser.objects.filter(username=Email, password=Pass)[0]
        user = authenticate(username=Email, password=Pass)

        # ユーザー認証
        if user:
            login(request, user)
            print("a")
            if user.is_teacher:
                
                return HttpResponseRedirect(reverse('teacher'))
            else:
                return HttpResponseRedirect(reverse('user_'))

            
        else:
            return HttpResponse("ログインIDまたはパスワードが間違っています")
    # GET
    else:
        return render(request, 'login/login1.html')


class MyLogoutView(LogoutView):
    template_name = 'login/logout.html'

class MyteacherView(LoginRequiredMixin, TemplateView):
    template_name = 'school/teacher.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["schedulekey"] = ScheduleForm()
        context["daydutykey"] = DaydutyForm()
        context['teacher'] = self.request.user
        
        return context

def logout_request(request):
    logout(request)
    return redirect('login')








class MyUserView(LoginRequiredMixin, TemplateView):
    template_name = 'login/user.html'
    
    def get_context_data(self, **kwargs):
        PLACE_CHOICES = ["教室ほうき","教室机寄せ","教室モップ","黒板","理科室","男子トイレ","女子トイレ","美化委員の仕事"]
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        user = self.request.user
        if MessageModel.objects.filter(teacher__classnum = user.classnum,teacher__gradenum = user.gradenum):
            context['message'] = MessageModel.objects.filter(teacher__classnum = user.classnum,teacher__gradenum = user.gradenum).order_by("created_at").reverse().all()
            
        cm = CleaningModel.objects.filter(user = self.request.user.id)[0] 
        context['cleaningplace'] = PLACE_CHOICES[cm.place]
        sl = SchoolLunchModel.objects.filter(user = self.request.user.id)[0]
        context['schoollunch'] = sl.ABC
        dd = DayDutyModel.objects.filter(classnum = self.request.user.classnum, gradenum = self.request.user.gradenum)[0]
        dd_user = CustomUser.objects.filter(classnum = self.request.user.classnum, gradenum = self.request.user.gradenum, attendancenum = dd.current_number)[0]
        context['dd_fullname'] = dd_user.last_name + dd_user.first_name
        sm = ScheduleModel.objects.filter(classnum = self.request.user.classnum, gradenum = self.request.user.gradenum)[0]
        subject = {'国':'国語', '数':'数学','理':'理科','社':'社会','英':'英語','美':'美術','体':'体育','家':'家庭科','技':'技術','音':'音楽','道':'道徳','総':'総合','学':'学活'}
        schedule = [[],[],[],[],[],[]]
        week = [sm.monday,sm.tuesday,sm.wednesday,sm.thursday,sm.friday]
        for w in week:
            for i in range(len(w)):
                schedule[i].append(subject[w[i]])
            if len(w) < 6:
                for j in range(len(w),6):
                    schedule[j].append("")
        print(schedule)
        context["schedule"] = schedule


        return context
        

class MyOtherView(LoginRequiredMixin, TemplateView):
    template_name = 'login/other.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.exclude(username=self.request.user.username)
        
        return context


def check(input):
    subject = {'国','数','理','社','英','美','体','家','技','音','道','総','学'}
    flag = True
    for v in input:
        if v not in subject:
            flag = False

    return flag







class TeacherView(LoginRequiredMixin, TemplateView):
    template_name = 'school/teacher.html'
    # def get(self, request):
    #     return render(request, self.template_name, self.params)

    def post(self, request):
        # context=super().post(request, *args,**kwargs)
        context={}
        # form =ScheduleForm(request.POST)
        print(request.POST)
        print("message" in request.POST)
        print("is_important" in request.POST)
        if 'monday' in request.POST and check(request.POST.get('monday')) and check(request.POST.get('tuesday')) and check(request.POST.get('wednesday')) and check(request.POST.get('thursday')) and check(request.POST.get('friday')):
            sm = ScheduleModel.objects.filter(classnum = self.request.user.classnum, gradenum = self.request.user.gradenum)[0]
            sm.monday=request.POST.get('monday')
            sm.tuesday=request.POST.get('tuesday')
            sm.wednesday=request.POST.get('wednesday')
            sm.thursday=request.POST.get('thursday')
            sm.friday=request.POST.get('friday')
            sm.save()
            context=self.get_context_data()
        elif 'current_number' in request.POST:
            dd = DayDutyModel.objects.filter(classnum = self.request.user.classnum, gradenum = self.request.user.gradenum)[0]
            dd.current_number = request.POST.get('current_number')
            dd.save()
            context=self.get_context_data()
        elif ("message" in request.POST) and ("is_important" in request.POST):
            MessageModel.objects.create(teacher = self.request.user, message = request.POST.get("message"),category = 1)
            context=self.get_context_data()
        elif ("message" in request.POST):
            MessageModel.objects.create(teacher = self.request.user, message = request.POST.get("message"),category = 0)
            context=self.get_context_data()

        else:
            context=self.get_context_data()
            context['error_message']= "入力項目をもう一度確認してください。"
            



        return render(request, self.template_name, context)
    
        

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = CustomUser.objects.get(username=self.request.user.username)
        dd = DayDutyModel.objects.filter(classnum = self.request.user.classnum, gradenum = self.request.user.gradenum)[0]
        dd_user = CustomUser.objects.filter(classnum = self.request.user.classnum, gradenum = self.request.user.gradenum, attendancenum = dd.current_number)[0]
        context['classnum'] = self.request.user.classnum
        context['gradenum'] = self.request.user.gradenum
        context['dd_fullname'] = dd_user.last_name + dd_user.first_name
        sm = ScheduleModel.objects.filter(classnum = self.request.user.classnum, gradenum = self.request.user.gradenum)[0]
        subject = {'国':'国語', '数':'数学','理':'理科','社':'社会','英':'英語','美':'美術','体':'体育','家':'家庭科','技':'技術','音':'音楽','道':'道徳','総':'総合','学':'学活'}
        schedule = [[],[],[],[],[],[]]
        week = [sm.monday,sm.tuesday,sm.wednesday,sm.thursday,sm.friday]
        for w in week:
            for i in range(len(w)):
                schedule[i].append(subject[w[i]])
            if len(w) < 6:
                for j in range(len(w),6):
                    schedule[j].append("")
        print(schedule)
        context["schedule"] = schedule
        scheduleForm = ScheduleForm()
        daydutyForm = DaydutyForm()
        messageForm = MessageForm()
        scheduleForm.fields['monday'].initial = sm.monday
        scheduleForm.fields['tuesday'].initial = sm.tuesday
        scheduleForm.fields['wednesday'].initial = sm.wednesday
        scheduleForm.fields['thursday'].initial = sm.thursday
        scheduleForm.fields['friday'].initial = sm.friday
        daydutyForm.fields['current_number'].initial = dd.current_number
        context["form_schedule"] = scheduleForm
        context["form_dayduty"] = daydutyForm
        context["form_message"] = messageForm

        self.params = context

school_app/templates/school/anything.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
</head>
<body>
    <h1>{{ school }}</h1>
    <p>{{ ab }}</p>
    <a href= "{%url 'school'%}">スクールurl</a>
    <h1>{{ msg }}</h1>
    <h1>{{ title }}</h1>

    
</body>
</html>

school_app/templates/school/teacher.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>あなたの情報</title>
    <link rel="stylesheet" href="./css/style.css">
    <style type="text/css">
      @import url('https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap');
      .carousel-text{
        text-shadow:1px 2px 1px rgb(200, 199, 199);
      }

        .carousel-inner img{
        /* position: absolute; */
        margin-left:auto;
        margin-right:auto;
        width:60%;
        height: 10%;
        font-family: 'Kosugi Maru', sans-serif;
  }
  table{
  width: 80%;
  margin-top:30px;
  margin-left:auto;
  margin-right:auto;
  border-collapse:separate;
  border-spacing: 0;
  font-family: 'Kosugi Maru', sans-serif;
  /* filter:drop-shadow(10px 10px 10px rgba(0,0,0,0.6)); */
}

table th:first-child{
  border-radius: 5px 0 0 0;
  width:8%;
}
table td:first-child{
  border-radius: 5px 0 0 0;
  width:8%;
}

table td:last-child{
  /* border-radius: 0 5px 0 0; */
  border-right: 1px solid #db9aea;
}

table th{
  text-align: center;
  color:white;
  background: linear-gradient(#db9aea,#efb1f3);
  /* border-right: 1px solid #db9aea; */
  border-left: 1px solid #db9aea;
  border-top: 1px solid #db9aea;
  border-bottom: 1px solid #db9aea;
  font-family: 'Kosugi Maru', sans-serif;


  box-shadow: 0px 1px 1px rgba(255,255,255,0.3) inset;
  width: 18%;
  padding: 10px 0;
}

table td{
  text-align: center;
  border-left: 1px solid #db9aea;
  /* border-right: 1px solid #db9aea; */
  border-bottom: 1px solid #db9aea;
  border-top:none;
  /* box-shadow: 0px -3px 5px 1px #e7d0ec) inset; */
  width: 18%;
  padding: 10px 0;
  border-radius: 3px;
  font-weight:bold;
  font-family: 'Kosugi Maru', sans-serif;
}
#title{

  flex-direction:row;
  display:flex;

}
body {
  background-color:rgb(252, 237, 250);
  border-radius:3px;
}
.current_num{
  background-color: rgb(255, 254, 254);
  border-radius:3px;
}
.current_num:focus{
  border-radius:3px;
  border:solid 2px #EEA34A;
}
.current_num:hover{
  border:solid 2px #EEA34A;
  border-radius:3px;
}
.monday{
  background-color: rgb(255, 255, 255);
  border-radius:3px;
  margin-top:2px;
  font-family: 'Kosugi Maru', sans-serif;
}
.monday:focus {
    border:solid 2px #EEA34A;
}
.monday:hover {
    border:solid 2px #EEA34A;
    border-radius:3px;
}
.tuesday{
  background-color: rgb(255, 255, 255);
  border-radius:3px;
  margin-top:2px;
  font-family: 'Kosugi Maru', sans-serif;
}
.tuesday:focus {
    border:solid 2px #EEA34A;
}
.tuesday:hover {
    border:solid 2px #EEA34A;
    border-radius:3px;
}

.wednesday{
  background-color: rgb(255, 255, 255);
  border-radius:3px;
  margin-top:2px;
  font-family: 'Kosugi Maru', sans-serif;
}
.wedenesday:focus {
    border:solid 2px #EEA34A;
}
.wednesday:hover {
    border:solid 2px #EEA34A;
    border-radius:3px;
}

.thursday{
  background-color: rgb(255, 255, 255);
  border-radius:3px;
  font-family: 'Kosugi Maru', sans-serif;
}
.thursday:focus {
    border:solid 3px #EEA34A;
}
.thursday:hover {
    border:solid 2px #EEA34A;
    border-radius:3px;
}
.friday{
    border-radius:3px;
    margin-top:2px;
    font-family: 'Kosugi Maru', sans-serif;
}
.friday:focus {
    border:solid 2px #EEA34A;
    border-radius:3px;
}
.friday:hover {
    border:solid 2px #EEA34A;
    border-radius:3px;
}
input:focus{
  outline: none;
  border-radius:3px;
}
label{
  font-weight:bold;
  margin-top:10px;
  font-size:20px;
  font-family: 'Kosugi Maru', sans-serif;
}
.buttton{
  display       : inline-block;
  border-radius : 5%;          /* 角丸       */
  font-size     : 18pt;        /* 文字サイズ */
  text-align    : center;      /* 文字位置   */
  cursor        : pointer;     /* カーソル   */
  padding       : 12px 12px;   /* 余白       */
  background    : #db9aea;     /* 背景色     */
  color         : #ffffff;     /* 文字色     */
  line-height   : 1em;         /* 1行の高さ  */
  transition    : .3s;         /* なめらか変化 */
  box-shadow    : 6px 6px 3px #666666;  /* 影の設定 */
  border        : 2px solid #db9aea;    /* 枠の指定 */
  font-family: 'Kosugi Maru', sans-serif;
}
.buttton:hover{
  box-shadow    : none;        /* カーソル時の影消去 */
  color         : #db9aea;     /* 背景色     */
  background    : #ffffff;     /* 文字色     */
}
.butttton{
  display       : inline-block;
  border-radius : 5%;          /* 角丸       */
  font-size     : 18pt;        /* 文字サイズ */
  text-align    : center;      /* 文字位置   */
  cursor        : pointer;     /* カーソル   */
  padding       : 12px 12px;   /* 余白       */
  background    : #db9aea;     /* 背景色     */
  color         : #ffffff;     /* 文字色     */
  line-height   : 1em;         /* 1行の高さ  */
  transition    : .3s;         /* なめらか変化 */
  box-shadow    : 6px 6px 3px #666666;  /* 影の設定 */
  border        : 2px solid #db9aea;    /* 枠の指定 */
  font-family: 'Kosugi Maru', sans-serif;
}
.butttton:hover{
  box-shadow    : none;        /* カーソル時の影消去 */
  color         : #db9aea;     /* 背景色     */
  background    : #ffffff;     /* 文字色     */
}
#button2{
  margin-top:20px;
  margin-bottom:20px;
  font-family: 'Kosugi Maru', sans-serif;
}
#botton3{
  font-family: 'Kosugi Maru', sans-serif;
  position:relative;
}
#button3 textarea{
  margin-left:150px;
}
#button3 label[for="id_message"]{
  justify-self:flex-start;
  align-self:flex-start;
  bottom:500px;
  position:absolute;
  width:150px;
}
.navbar-brand{
  font-family: 'Kosugi Maru', sans-serif;
}
.nav-link{
  font-family: 'Kosugi Maru', sans-serif;
}
        
        </style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light" style="background: linear-gradient(#db9aea,#efb1f3); height:70px;" >
    <div class="container-fluid">
      <a class="navbar-brand" href="#" style="color:rgb(255, 255, 255); font-weight:bold;">学校生活効率化App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>



      <div class="collapse navbar-collapse" id="navbarNav" style="padding-top:20px;">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <p class="nav-link" id="check" aria-current="page" href="" style="color:rgb(255, 255, 255); font-weight:bold;">ユーザー情報</p>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://kuwae-j.edumap.jp/" role="button" style="color:rgb(255, 255, 255); font-weight:bold;">学校ホームページ</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'logout'%}" role="button" style="color:rgb(255, 255, 255); font-weight:bold;">ログアウト</a>
          </li>
          <li class="nav-item">
            <p class="nav-link"id="time"style="padding-left:520px;" style="color:rgb(255, 255, 255); font-weight:bold;">現在時刻</p>
        </li>

        </ul>
        <ul class="navbar-nav ml-auto ">
          <li class ="nav-item">
          </li>
        </ul>
      </div>
      

    </div>
  </nav>
  </nav>

      <br>
      <form action="{% url 'teacher' %}" enctype="multipart/form-data" method="POST" id=button1>
        {% csrf_token %}
        {{ form_dayduty }}
        <input type="submit" value="変更" class ="buttton">
    </form>

      <p>{{error_message}}</p>
    <form action="{% url 'teacher' %}" enctype="multipart/form-data" method="POST" id=button2>
        {% csrf_token %}
        {{ form_schedule }}
        <input type="submit" value="変更" class ="butttton">
    </form>

    <form action="{% url 'teacher' %}" enctype="multipart/form-data" method="POST" id=button3>
      {% csrf_token %}
      {{ form_message }}
      <input type="submit" value="変更" class ="butttton">
  </form>


    <table>
        <tr>
        <th></th>
        <th>月曜日</th>
        <th>火曜日</th>
        <th>水曜日</th>
        <th>木曜日</th>
        <th>金曜日</th>
        
        </tr>
        {% for row in schedule  %}
        <tr>
          <td>{{forloop.counter}}</td>
        {%for r in row%}
        
        <td>{{r}}</td>
        {%endfor%}
        </tr>
        {%endfor%}
        </table>




    <br><br><br><br><br><br><br><br>
    <h1>
    </h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>

</html>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;       
        }

        var csrftoken = getCookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $(document).ready(function() {
                    $("#check").on('click', function(){
                    Swal.fire({
                        title
                        
                        : 'ユーザー情報',
                        html: `<p>ユーザー名:{{user.username}}</p>
                                <p>氏名:{{user.last_name}} {{user.first_name}}</p>
                                <p>メールアドレス:{{user.email}}</p>
                                <p>{{user.gradenum}}年{{user.classnum}}組{{user.attendancenum}}番</p>
                                <p>アカウント作成日：{{user.date_joined}}</p>

                        `,
                        confirmButtonText: '閉じる',
                        type: 'confirm',
                        });
                    });
                    $(function(){
                    setInterval(function(){
                    var now = new Date();
                    var y = now.getFullYear();
                    var m = now.getMonth() + 1;
                    var d = now.getDate();
                    var w = now.getDay();

                    var wd = ['日', '月', '火', '水', '木', '金', '土'];
                    var h = now.getHours();
                    var mi = now.getMinutes();
                    var s = now.getSeconds();
                    $('#time').text('現在時刻は'+y + '年' + m + '月' + d + '日' + h + '時' + mi + '分' + s + '秒' + '(' + wd[w] + ')');
                    }, 1000);
                    });
                    $('#time').css({'font-weight':'bold','color':'white'});
                });
    </script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>